### PR TITLE
initial addition of evidence API

### PR DESCRIPTION
**Pull request by droessmj**
New Evidence API endpoint for Lacework Python SDK

### CODE REVIEW

**Comment by droessmj** [comment]
I'll be honest - I don't know what I don't know about where I may have missed modifications. I do know that happy path tests out.

**Comment by kiddinn** [comment]
sorry, didn't see this, added #65  that also adds in the evidence API along with some other changes, I also see that you are not using the search endpoint

**Comment by kiddinn** [comment]
also looking at https://yourlacework.lacework.net/api/v2/docs-beta#tag/Evidence I don't see any support for any other call than the `search` endpoint, that also seems to confirm with other API documentation

**Comment by alannix-lw** [comment]
Resolved with #65

**Pull request closed without merging**
